# Generated by Django 2.2.19 on 2022-09-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_auto_20220927_1427"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-pub_date",)},
        ),
    ]
