# Generated by Django 2.2.6 on 2022-10-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_postmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostModel",
        ),
    ]
